In [2]:
# average vs mean

import numpy as np
a = np.array([np.random.randint(0, 20, 5), np.random.randint(0, 20, 5)])
print('原始数据\n', a)
print('mean函数'.center(20, '*'))
print('对所有数据计算\n', a.mean())
print('axis=0，按行方向计算，即每列\n', a.mean(axis=0))  # 按行方向计算，即每列
print('axis=1，按列方向计算，即每行\n', a.mean(axis=1))  # 按列方向计算，即每行
print('average函数'.center(20, '*'))
print('对所有数据计算\n', np.average(a))
print('axis=0，按行方向计算，即每列\n', np.average(a, axis=0))  # 按行方向计算，即每列
print('axis=1，按列方向计算，即每行\n', np.average(a, axis=1))  # 按列方向计算，即每行
b = np.array([1, 2, 3, 4])
wts = np.array([4, 3, 2, 1])
print('不指定权重\n', np.average(b))
print('指定权重\n', np.average(b, weights=wts))

原始数据
 [[11  8  3  6 18]
 [10  6  1  0  6]]
*******mean函数*******
对所有数据计算
 6.9
axis=0，按行方向计算，即每列
 [10.5  7.   2.   3.  12. ]
axis=1，按列方向计算，即每行
 [9.2 4.6]
*****average函数******
对所有数据计算
 6.9
axis=0，按行方向计算，即每列
 [10.5  7.   2.   3.  12. ]
axis=1，按列方向计算，即每行
 [9.2 4.6]
不指定权重
 2.5
指定权重
 2.0


In [20]:
import scipy.optimize as op
def Sigmoid(z):
    return 1/(1 + np.exp(-z));

def Gradient(theta,x,y):
    m , n = x.shape
    theta = theta.reshape((n,1));
    y = y.reshape((m,1))
    sigmoid_x_theta = Sigmoid(x.dot(theta));
    grad = ((x.T).dot(sigmoid_x_theta-y))/m;
    return grad.flatten();

def CostFunc(theta,x,y):
    m,n = x.shape; 
    theta = theta.reshape((n,1));
    y = y.reshape((m,1));
    term1 = np.log(Sigmoid(x.dot(theta)));
    term2 = np.log(1-Sigmoid(x.dot(theta)));
    term1 = term1.reshape((m,1))
    term2 = term2.reshape((m,1))
    term = y * term1 + (1 - y) * term2;
    J = -((np.sum(term))/m);
    return J;

# intialize X and y
X = np.array([[1,2,3],[1,3,4]]);
y = np.array([[1],[0]]);

m , n = X.shape;
initial_theta = np.zeros(n);
# Result = op.minimize(fun = CostFunc, x0 = initial_theta, args = (X, y),method = 'TNC',jac = Gradient)
# optimal_theta = Result.x
initial_theta

array([0., 0., 0.])

In [ ]:
# empty array
a = np.empty((2,0))
a = np.append(a, np.array([[1],[2]]), axis=1)
a = np.append(a, np.array([[1],[2]]), axis=1)
a = np.append(a, np.array([[1],[2]]), axis=1)
a

In [48]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 1], [2, 2]])
a, b, a*b

array([[1, 2],
       [3, 4]])

In [33]:
a = np.array([1, 2])
b = np.array([4, 1])
a, b, np.dot(a,b)

(array([1, 2]), array([4, 1]))

In [63]:
b = np.array([[11,12,13], [14,15,16]])
b

array([[11, 12, 13],
       [14, 15, 16]])

In [69]:
test = np.append(a.flatten(), b.flatten())
test

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16])

In [70]:
np.reshape(test[], (2, 3), 'F')

array([[11, 13, 15],
       [12, 14, 16]])